all: help.indx news.indx plushelp.indx staffhelp.indx wizhelp.indx wiznews.indx

help.indx: help.txt
	./mkindx help.txt help.indx

news.indx: news.txt
	./mkindx news.txt news.indx

plushelp.indx: plushelp.txt
	./mkindx plushelp.txt plushelp.indx

staffhelp.indx: staffhelp.txt
	./mkindx staffhelp.txt staffhelp.indx

wizhelp.indx: wizhelp.txt
	./mkindx wizhelp.txt wizhelp.indx

wiznews.indx: wiznews.txt
	./mkindx wiznews.txt wiznews.indx

