#!/bin/sh
PATH=/bin:/usr/bin:
#
#	Convert from arbitrary format to MUX V2 GDBM format.
#
case $# in
	1)	../bin/dbconvert $1 X ;;
	2)	../bin/dbconvert $1 X <$2 ;;
	3)	../bin/dbconvert $1 X <$2 >$3 ;;
	*)	echo Usage: $0 'gdbm_file [source_file [dest_file]]'; exit 1 ;;
esac

exit 0
