#!/bin/sh
PATH=/bin:/usr/bin:
#
#	Convert from CHashFile format to MUX V2 flat file format.
#
echo NOTE: Make sure the MUX is NOT running before you make a flatfile. 
case $# in
	1)	../bin/dbconvert $1 x ;;
	2)	../bin/dbconvert $1 x <$2 ;;
	3)	../bin/dbconvert $1 x <$2 >$3 ;;
	*)	echo Usage: $0 'basename [structfile [flatfile]]';
                echo i.e., $0 netmux netmux.db netmux.flat;
                exit 1 ;;
esac

exit 0
