/*
 * unicode_tables_c.h — Unicode case mapping DFA tables for pure C.
 *
 * THIS FILE IS GENERATED by 'make' in the utf/ directory.
 * DO NOT EDIT — changes will be overwritten.
 *
 * Provides the same DFA-driven case mapping as mux_toupper/mux_tolower/
 * mux_totitle from stringutil.h, but as standalone C functions using
 * tables generated by the utf/ pipeline tools.
 *
 * DFA execution model:
 *   Feed bytes to the DFA one at a time.  When it reaches an accepting
 *   state, the state index encodes either "identity" (no change) or an
 *   index into the OTT (output text table).  OTT entries are either
 *   literal replacements or XOR masks.
 */

#ifndef UNICODE_TABLES_C_H
#define UNICODE_TABLES_C_H

#include <stddef.h>

/* Default LIBMUX_API when not provided by config.h. */
#ifndef LIBMUX_API
#if defined(_WIN32) || defined(WIN32)
#ifdef BUILDING_LIBMUX
#define LIBMUX_API __declspec(dllexport)
#else
#define LIBMUX_API __declspec(dllimport)
#endif
#else
#define LIBMUX_API __attribute__((visibility("default")))
#endif
#endif

/* Equivalent to MUX's string_desc — holds a UTF-8 replacement string. */
typedef struct {
    size_t n_bytes;
    size_t n_points;
    const unsigned char *p;
} co_string_desc;

/* UTF-8 lead byte -> sequence length (1-4), 5=continuation, 6=illegal */
#define CO_UTF8_SIZE1     1
#define CO_UTF8_SIZE2     2
#define CO_UTF8_SIZE3     3
#define CO_UTF8_SIZE4     4
#define CO_UTF8_CONTINUE  5
#define CO_UTF8_ILLEGAL   6

#ifdef __cplusplus
extern "C" {
#endif

extern LIBMUX_API const unsigned char utf8_FirstByte[256];

// utf/tr_tolower.txt
//
// 1460 code points.
// 62 states, 87 columns, 2080 bytes
//
#define TR_TOLOWER_START_STATE (0)
#define TR_TOLOWER_ACCEPTING_STATES_START (62)
extern LIBMUX_API const unsigned char tr_tolower_itt[256];
extern LIBMUX_API const unsigned short tr_tolower_sot[62];
extern LIBMUX_API const unsigned char tr_tolower_sbt[1700];

#define TR_TOLOWER_DEFAULT (0)
#define TR_TOLOWER_LITERAL_START (1)
#define TR_TOLOWER_XOR_START (28)
extern LIBMUX_API const co_string_desc tr_tolower_ott[144];

// utf/tr_toupper.txt
//
// 1552 code points.
// 68 states, 90 columns, 4242 bytes
//
#define TR_TOUPPER_START_STATE (0)
#define TR_TOUPPER_ACCEPTING_STATES_START (68)
extern LIBMUX_API const unsigned char tr_toupper_itt[256];
extern LIBMUX_API const unsigned short tr_toupper_sot[68];
extern LIBMUX_API const unsigned short tr_toupper_sbt[1925];

#define TR_TOUPPER_DEFAULT (0)
#define TR_TOUPPER_LITERAL_START (1)
#define TR_TOUPPER_XOR_START (97)
extern LIBMUX_API const co_string_desc tr_toupper_ott[230];

// utf/tr_totitle.txt
//
// 1529 code points.
// 68 states, 90 columns, 4152 bytes
//
#define TR_TOTITLE_START_STATE (0)
#define TR_TOTITLE_ACCEPTING_STATES_START (68)
extern LIBMUX_API const unsigned char tr_totitle_itt[256];
extern LIBMUX_API const unsigned short tr_totitle_sot[68];
extern LIBMUX_API const unsigned short tr_totitle_sbt[1880];

#define TR_TOTITLE_DEFAULT (0)
#define TR_TOTITLE_LITERAL_START (1)
#define TR_TOTITLE_XOR_START (70)
extern LIBMUX_API const co_string_desc tr_totitle_ott[201];

// utf/tr_foldmatch.txt
//
// 14 code points.
// 7 states, 11 columns, 310 bytes
//
#define TR_FOLDMATCH_START_STATE (0)
#define TR_FOLDMATCH_ACCEPTING_STATES_START (7)
extern LIBMUX_API const unsigned char tr_foldmatch_itt[256];
extern LIBMUX_API const unsigned char tr_foldmatch_sot[7];
extern LIBMUX_API const unsigned char tr_foldmatch_sbt[47];

#define TR_FOLDMATCH_DEFAULT (0)
#define TR_FOLDMATCH_LITERAL_START (1)
#define TR_FOLDMATCH_XOR_START (3)
extern LIBMUX_API const co_string_desc tr_foldmatch_ott[3];


#ifdef __cplusplus
} /* extern "C" */
#endif

/* In C++ mode, the OTT arrays are string_desc (from utf8tables.h) but these
 * functions return co_string_desc*.  The types are ABI-identical, so a cast
 * is safe.  In C mode, both sides are co_string_desc and no cast is needed.
 */
#ifdef __cplusplus
#define CO_OTT_CAST(x) reinterpret_cast<const co_string_desc *>(x)
#else
#define CO_OTT_CAST(x) (x)
#endif

/*
 * co_dfa_toupper — Run the toupper DFA on a single code point.
 *
 * p points to the first byte of a UTF-8 code point.
 * On return, *bXor is set:
 *   - returns NULL:  identity (no change)
 *   - bXor == 1:     XOR each byte of input with result->p[]
 *   - bXor == 0:     literal replacement (may differ in byte count)
 */
static inline const co_string_desc *co_dfa_toupper(const unsigned char *p, int *bXor)
{
    unsigned short iState = TR_TOUPPER_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_toupper_itt[ch];
        unsigned short iOffset = tr_toupper_sot[iState];
        for (;;)
        {
            int y = tr_toupper_sbt[iOffset];
            if (y < 128)
            {
                /* RUN phrase. */
                if (iColumn < y)
                {
                    iState = tr_toupper_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                /* COPY phrase. */
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_toupper_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_TOUPPER_ACCEPTING_STATES_START);

    if (TR_TOUPPER_DEFAULT == iState - TR_TOUPPER_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_TOUPPER_XOR_START <= iState - TR_TOUPPER_ACCEPTING_STATES_START);
        return CO_OTT_CAST(tr_toupper_ott + iState - TR_TOUPPER_ACCEPTING_STATES_START - 1);
    }
}

static inline const co_string_desc *co_dfa_tolower(const unsigned char *p, int *bXor)
{
    unsigned char iState = TR_TOLOWER_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_tolower_itt[ch];
        unsigned short iOffset = tr_tolower_sot[iState];
        for (;;)
        {
            int y = tr_tolower_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_tolower_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_tolower_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_TOLOWER_ACCEPTING_STATES_START);

    if (TR_TOLOWER_DEFAULT == iState - TR_TOLOWER_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_TOLOWER_XOR_START <= iState - TR_TOLOWER_ACCEPTING_STATES_START);
        return CO_OTT_CAST(tr_tolower_ott + iState - TR_TOLOWER_ACCEPTING_STATES_START - 1);
    }
}

static inline const co_string_desc *co_dfa_totitle(const unsigned char *p, int *bXor)
{
    unsigned short iState = TR_TOTITLE_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_totitle_itt[ch];
        unsigned short iOffset = tr_totitle_sot[iState];
        for (;;)
        {
            int y = tr_totitle_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_totitle_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_totitle_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_TOTITLE_ACCEPTING_STATES_START);

    if (TR_TOTITLE_DEFAULT == iState - TR_TOTITLE_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_TOTITLE_XOR_START <= iState - TR_TOTITLE_ACCEPTING_STATES_START);
        return CO_OTT_CAST(tr_totitle_ott + iState - TR_TOTITLE_ACCEPTING_STATES_START - 1);
    }
}

static inline const co_string_desc *co_dfa_foldmatch(const unsigned char *p, int *bXor)
{
    int iState = TR_FOLDMATCH_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_foldmatch_itt[ch];
        unsigned short iOffset = tr_foldmatch_sot[iState];
        for (;;)
        {
            int y = tr_foldmatch_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_foldmatch_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_foldmatch_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_FOLDMATCH_ACCEPTING_STATES_START);

    if (TR_FOLDMATCH_DEFAULT == iState - TR_FOLDMATCH_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_FOLDMATCH_XOR_START <= iState - TR_FOLDMATCH_ACCEPTING_STATES_START);
        return CO_OTT_CAST(tr_foldmatch_ott + iState - TR_FOLDMATCH_ACCEPTING_STATES_START - 1);
    }
}

#endif /* UNICODE_TABLES_C_H */
