/*! \file utf8_collate.cpp
 * \brief Unicode Collation Algorithm (UCA) implementation per UTS #10.
 *
 * Provides linguistically correct string comparison using the Default
 * Unicode Collation Element Table (DUCET) from Unicode 16.0.
 *
 * All lookups use DFA state machines generated by integers.exe and
 * pairs.exe.  Implicit weights for CJK and unassigned code points
 * are computed algorithmically per UCA Section 10.1.
 */

#include "copyright.h"
#include "autoconf.h"
#include "config.h"
#include "core.h"

#include "ducet_cetable.h"

// ---------------------------------------------------------------------------
// CE weight unpacking from uint32_t.
//
// Packed format:
//   Bit  31:    variable flag
//   Bits 30-16: primary weight (15 bits)
//   Bits 15-5:  secondary weight (11 bits)
//   Bits 4-0:   tertiary weight (5 bits)
// ---------------------------------------------------------------------------

#define CE_PRIMARY(w)   (((w) >> 16) & 0x7FFF)
#define CE_SECONDARY(w) (((w) >> 5) & 0x07FF)
#define CE_TERTIARY(w)  ((w) & 0x1F)
#define CE_VARIABLE(w)  (((w) >> 31) & 1)

// ---------------------------------------------------------------------------
// DFA lookup: single code point -> CE index.
// Returns 0 if not in DUCET (use implicit weights).
// ---------------------------------------------------------------------------

static int GetDUCET(const UTF8 *p, const UTF8 *pEnd)
{
    int iState = TR_DUCET_START_STATE;
    while (p < pEnd)
    {
        unsigned char ch = *p++;
        int iColumn = tr_ducet_itt[ch];
        int iOffset = tr_ducet_sot[iState];

        for (;;)
        {
            int y = tr_ducet_sbt[iOffset];
            if (y < 128)
            {
                // RUN phrase.
                if (iColumn < y)
                {
                    iState = tr_ducet_sbt[iOffset + 1];
                    break;
                }
                iColumn -= y;
                iOffset += 2;
            }
            else
            {
                // COPY phrase.
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_ducet_sbt[iOffset + iColumn + 1];
                    break;
                }
                iColumn -= y;
                iOffset += y + 1;
            }
        }
    }

    if (iState >= TR_DUCET_ACCEPTING_STATES_START)
    {
        return iState - TR_DUCET_ACCEPTING_STATES_START;
    }
    return 0;
}

// ---------------------------------------------------------------------------
// DFA lookup: two-code-point contraction -> CE index.
// Returns 0 if no contraction match.
// ---------------------------------------------------------------------------

static int GetContraction(const UTF8 *p1, const UTF8 *p1End,
                          const UTF8 *p2, const UTF8 *p2End)
{
    int iState = TR_DUCET_CONTRACT_START_STATE;

    // Feed first code point's bytes.
    //
    while (p1 < p1End && iState < TR_DUCET_CONTRACT_ACCEPTING_STATES_START)
    {
        unsigned char ch = *p1++;
        int iColumn = tr_ducet_contract_itt[ch];
        int iOffset = tr_ducet_contract_sot[iState];

        for (;;)
        {
            int y = tr_ducet_contract_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_ducet_contract_sbt[iOffset + 1];
                    break;
                }
                iColumn -= y;
                iOffset += 2;
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_ducet_contract_sbt[iOffset + iColumn + 1];
                    break;
                }
                iColumn -= y;
                iOffset += y + 1;
            }
        }
    }

    // Feed second code point's bytes.
    //
    while (p2 < p2End && iState < TR_DUCET_CONTRACT_ACCEPTING_STATES_START)
    {
        unsigned char ch = *p2++;
        int iColumn = tr_ducet_contract_itt[ch];
        int iOffset = tr_ducet_contract_sot[iState];

        for (;;)
        {
            int y = tr_ducet_contract_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_ducet_contract_sbt[iOffset + 1];
                    break;
                }
                iColumn -= y;
                iOffset += 2;
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_ducet_contract_sbt[iOffset + iColumn + 1];
                    break;
                }
                iColumn -= y;
                iOffset += y + 1;
            }
        }
    }

    if (iState >= TR_DUCET_CONTRACT_ACCEPTING_STATES_START)
    {
        int idx = iState - TR_DUCET_CONTRACT_ACCEPTING_STATES_START;
        if (0 != idx)
        {
            // The result table stores CE indices as UTF32 values.
            //
            return static_cast<int>(tr_ducet_contract_nfc_compose_result[idx]);
        }
    }
    return 0;
}

// ---------------------------------------------------------------------------
// Advance one UTF-8 code point and return the pointer past it.
// ---------------------------------------------------------------------------

static const UTF8 *utf8_advance_collate(const UTF8 *p, const UTF8 *pEnd)
{
    if (p >= pEnd)
    {
        return p;
    }
    int n = utf8_FirstByte[*p];
    if (n < 1 || n >= UTF8_CONTINUE)
    {
        return p + 1;
    }
    for (int i = 1; i < n; i++)
    {
        if (  p + i >= pEnd
           || UTF8_CONTINUE != utf8_FirstByte[p[i]])
        {
            return p + 1;
        }
    }
    UTF32 cp = utf8_decode_raw(p, n);
    if (!utf8_is_valid_scalar(cp, n))
    {
        return p + 1;
    }
    const UTF8 *pNext = p + n;
    return (pNext <= pEnd) ? pNext : pEnd;
}

// ---------------------------------------------------------------------------
// Decode one UTF-8 code point from [p, pEnd). Returns UNI_EOF on error.
// ---------------------------------------------------------------------------
static UTF32 utf8_decode_collate(const UTF8 *p, const UTF8 *pEnd)
{
    if (p >= pEnd)
    {
        return UNI_EOF;
    }

    int n = utf8_FirstByte[*p];
    if (n < 1 || n >= UTF8_CONTINUE)
    {
        return UNI_EOF;
    }
    if (p + n > pEnd)
    {
        return UNI_EOF;
    }
    for (int i = 1; i < n; i++)
    {
        if (UTF8_CONTINUE != utf8_FirstByte[p[i]])
        {
            return UNI_EOF;
        }
    }

    UTF32 cp = utf8_decode_raw(p, n);
    if (!utf8_is_valid_scalar(cp, n))
    {
        return UNI_EOF;
    }
    return cp;
}

// ---------------------------------------------------------------------------
// Implicit weight computation (UCA Section 10.1).
//
// Code points not in DUCET get synthetic collation elements derived
// from their code point value.  The primary weight is split into
// a base and an offset within a designated range.
//
// For CJK unified ideographs (and extensions), the base depends on
// the block.  For all other unassigned code points, a default base
// is used.
// ---------------------------------------------------------------------------

// CJK Unified Ideographs ranges and their DUCET bases.
//
struct ImplicitRange
{
    UTF32 start;
    UTF32 end;
    unsigned short base;
};

static const ImplicitRange s_ImplicitRanges[] =
{
    // CJK Unified Ideographs.
    { 0x4E00,  0x9FFF,  0xFB40 },
    // CJK Compatibility Ideographs.
    { 0xF900,  0xFAFF,  0xFB40 },
    // CJK Unified Ideographs Extension A.
    { 0x3400,  0x4DBF,  0xFB80 },
    // CJK Unified Ideographs Extension B.
    { 0x20000, 0x2A6DF, 0xFB80 },
    // CJK Unified Ideographs Extension C.
    { 0x2A700, 0x2B73F, 0xFB80 },
    // CJK Unified Ideographs Extension D.
    { 0x2B740, 0x2B81F, 0xFB80 },
    // CJK Unified Ideographs Extension E.
    { 0x2B820, 0x2CEAF, 0xFB80 },
    // CJK Unified Ideographs Extension F.
    { 0x2CEB0, 0x2EBEF, 0xFB80 },
    // CJK Unified Ideographs Extension G.
    { 0x30000, 0x3134F, 0xFB80 },
    // CJK Unified Ideographs Extension H.
    { 0x31350, 0x323AF, 0xFB80 },
    // CJK Unified Ideographs Extension I.
    { 0x2EBF0, 0x2F7FF, 0xFB80 },
    // Tangut and Tangut Supplement (@implicitweights).
    { 0x17000, 0x18AFF, 0xFB00 },
    { 0x18D00, 0x18D7F, 0xFB00 },
    // Nushu (@implicitweights).
    { 0x1B170, 0x1B2FF, 0xFB01 },
    // Khitan Small Script (@implicitweights).
    { 0x18B00, 0x18CFF, 0xFB02 },
};

static const int s_nImplicitRanges =
    static_cast<int>(sizeof(s_ImplicitRanges) / sizeof(s_ImplicitRanges[0]));

// Compute the implicit primary weight for a code point.
// Returns AAAA (high 16 bits) and BBBB (low 16 bits) as a pair.
// The full implicit CE is [.AAAA.0020.0002][.BBBB.0000.0000].
//
static void ImplicitWeight(UTF32 cp, unsigned short &aaaa, unsigned short &bbbb)
{
    unsigned short base = 0xFBC0;  // Default for unassigned.

    for (int i = 0; i < s_nImplicitRanges; i++)
    {
        if (cp >= s_ImplicitRanges[i].start && cp <= s_ImplicitRanges[i].end)
        {
            base = s_ImplicitRanges[i].base;
            break;
        }
    }

    aaaa = base + static_cast<unsigned short>(cp >> 15);
    bbbb = static_cast<unsigned short>((cp & 0x7FFF) | 0x8000);
}

// ---------------------------------------------------------------------------
// Maximum CEs we collect per string.  18 CEs per code point max,
// LBUF_SIZE / 1 = 8000 code points worst case.  In practice, MUD
// strings are short.  We use a fixed buffer and bail to tiebreaker
// if we overflow.
// ---------------------------------------------------------------------------

// MUD strings are typically short.  LBUF_SIZE is 8000 bytes.
// Most code points produce 1-2 CEs.  4096 CEs handles any
// realistic MUD string with room to spare.
//
#define MAX_SORT_CES 4096

// ---------------------------------------------------------------------------
// Collect collation elements for a UTF-8 string.
//
// Walks the string code-point by code-point, checks for contractions
// (peeking ahead), then single-CP DUCET lookup, then implicit weights.
//
// Stores packed uint32_t CEs into the provided array.
// Returns the number of CEs collected.
// ---------------------------------------------------------------------------

static int CollectCEs(const UTF8 *src, size_t nSrc, uint32_t *ces, int maxCEs)
{
    const UTF8 *p = src;
    const UTF8 *pEnd = src + nSrc;
    int nCEs = 0;

    while (p < pEnd && nCEs < maxCEs)
    {
        const UTF8 *pNext = utf8_advance_collate(p, pEnd);

        // Check for 2-CP contraction by peeking at the next code point.
        //
        int ceIndex = 0;
        const UTF8 *pConsumed = pNext;

        if (pNext < pEnd)
        {
            const UTF8 *pNext2 = utf8_advance_collate(pNext, pEnd);
            ceIndex = GetContraction(p, pNext, pNext, pNext2);
            if (0 != ceIndex)
            {
                pConsumed = pNext2;  // Consumed both code points.
            }
        }

        if (0 == ceIndex)
        {
            // No contraction.  Single-CP lookup.
            //
            ceIndex = GetDUCET(p, pNext);
        }

        if (0 != ceIndex)
        {
            // Found in DUCET.  Copy CEs from the table.
            //
            int start = ducet_ce_offset[ceIndex];
            int end = ducet_ce_offset[ceIndex + 1];
            for (int i = start; i < end && nCEs < maxCEs; i++)
            {
                ces[nCEs++] = ducet_ce_weights[i];
            }
        }
        else
        {
            // Not in DUCET.  Compute implicit weight.
            //
            UTF32 cp = utf8_decode_collate(p, pNext);
            if (UNI_EOF != cp)
            {
                unsigned short aaaa, bbbb;
                ImplicitWeight(cp, aaaa, bbbb);

                // Implicit CE 1: [.AAAA.0020.0002]
                //
                if (nCEs < maxCEs)
                {
                    ces[nCEs++] = (static_cast<uint32_t>(aaaa) << 16)
                                | (static_cast<uint32_t>(0x0020) << 5)
                                | 0x0002;
                }

                // Implicit CE 2: [.BBBB.0000.0000]
                //
                if (nCEs < maxCEs)
                {
                    ces[nCEs++] = static_cast<uint32_t>(bbbb) << 16;
                }
            }
        }

        p = pConsumed;
    }

    return nCEs;
}

// ---------------------------------------------------------------------------
// mux_collate_cmp: Compare two UTF-8 strings using UCA.
//
// Returns negative if a < b, 0 if equal, positive if a > b.
//
// Implements the multi-level comparison:
//   Level 1: primary weights (base character identity)
//   Level 2: secondary weights (accents)
//   Level 3: tertiary weights (case)
//   Tiebreaker: code-point order
// ---------------------------------------------------------------------------

int mux_collate_cmp(const UTF8 *a, size_t nA, const UTF8 *b, size_t nB)
{
    // Collect CEs for both strings.
    //
    uint32_t cesA[MAX_SORT_CES];
    uint32_t cesB[MAX_SORT_CES];
    int nCEsA = CollectCEs(a, nA, cesA, MAX_SORT_CES);
    int nCEsB = CollectCEs(b, nB, cesB, MAX_SORT_CES);

    // Level 1: Compare primary weights.
    // Skip CEs with primary weight 0 (secondary-only CEs).
    //
    int iA = 0, iB = 0;
    for (;;)
    {
        // Advance past zero-primary CEs.
        //
        while (iA < nCEsA && 0 == CE_PRIMARY(cesA[iA]))
        {
            iA++;
        }
        while (iB < nCEsB && 0 == CE_PRIMARY(cesB[iB]))
        {
            iB++;
        }

        if (iA >= nCEsA || iB >= nCEsB)
        {
            break;
        }

        unsigned short pA = CE_PRIMARY(cesA[iA]);
        unsigned short pB = CE_PRIMARY(cesB[iB]);
        if (pA < pB) return -1;
        if (pA > pB) return 1;

        iA++;
        iB++;
    }

    // If one string has remaining primaries, it's greater.
    //
    while (iA < nCEsA && 0 == CE_PRIMARY(cesA[iA])) iA++;
    while (iB < nCEsB && 0 == CE_PRIMARY(cesB[iB])) iB++;
    if (iA < nCEsA) return 1;   // a has more primaries.
    if (iB < nCEsB) return -1;  // b has more primaries.

    // Level 2: Compare secondary weights.
    // Skip CEs with secondary weight 0.
    //
    iA = 0;
    iB = 0;
    for (;;)
    {
        while (iA < nCEsA && 0 == CE_SECONDARY(cesA[iA]))
        {
            iA++;
        }
        while (iB < nCEsB && 0 == CE_SECONDARY(cesB[iB]))
        {
            iB++;
        }

        if (iA >= nCEsA || iB >= nCEsB)
        {
            break;
        }

        unsigned short sA = CE_SECONDARY(cesA[iA]);
        unsigned short sB = CE_SECONDARY(cesB[iB]);
        if (sA < sB) return -1;
        if (sA > sB) return 1;

        iA++;
        iB++;
    }

    while (iA < nCEsA && 0 == CE_SECONDARY(cesA[iA])) iA++;
    while (iB < nCEsB && 0 == CE_SECONDARY(cesB[iB])) iB++;
    if (iA < nCEsA) return 1;
    if (iB < nCEsB) return -1;

    // Level 3: Compare tertiary weights.
    // Skip CEs with tertiary weight 0.
    //
    iA = 0;
    iB = 0;
    for (;;)
    {
        while (iA < nCEsA && 0 == CE_TERTIARY(cesA[iA]))
        {
            iA++;
        }
        while (iB < nCEsB && 0 == CE_TERTIARY(cesB[iB]))
        {
            iB++;
        }

        if (iA >= nCEsA || iB >= nCEsB)
        {
            break;
        }

        unsigned char tA = CE_TERTIARY(cesA[iA]);
        unsigned char tB = CE_TERTIARY(cesB[iB]);
        if (tA < tB) return -1;
        if (tA > tB) return 1;

        iA++;
        iB++;
    }

    while (iA < nCEsA && 0 == CE_TERTIARY(cesA[iA])) iA++;
    while (iB < nCEsB && 0 == CE_TERTIARY(cesB[iB])) iB++;
    if (iA < nCEsA) return 1;
    if (iB < nCEsB) return -1;

    // Tiebreaker: binary code-point order.
    //
    size_t nMin = (nA < nB) ? nA : nB;
    int cmp = memcmp(a, b, nMin);
    if (0 != cmp)
    {
        return cmp;
    }
    if (nA < nB) return -1;
    if (nA > nB) return 1;
    return 0;
}

// ---------------------------------------------------------------------------
// mux_collate_sortkey: Generate a binary sort key for UCA comparison.
//
// The sort key can be compared with memcmp to get the same ordering
// as mux_collate_cmp.
//
// Format:
//   [primary weights, big-endian 16-bit] 0x0000
//   [secondary weights, big-endian 16-bit] 0x0000
//   [tertiary weights, 8-bit] 0x00
//
// Returns the number of bytes written to key.
// ---------------------------------------------------------------------------

size_t mux_collate_sortkey(const UTF8 *src, size_t nSrc,
                           UTF8 *key, size_t nKeyMax)
{
    uint32_t ces[MAX_SORT_CES];
    int nCEs = CollectCEs(src, nSrc, ces, MAX_SORT_CES);

    size_t pos = 0;

    // Level 1: primary weights (16-bit big-endian).
    //
    for (int i = 0; i < nCEs; i++)
    {
        unsigned short p = CE_PRIMARY(ces[i]);
        if (0 != p && pos + 2 <= nKeyMax)
        {
            key[pos++] = static_cast<UTF8>(p >> 8);
            key[pos++] = static_cast<UTF8>(p & 0xFF);
        }
    }

    // Level separator.
    //
    if (pos + 2 <= nKeyMax)
    {
        key[pos++] = 0;
        key[pos++] = 0;
    }

    // Level 2: secondary weights (16-bit big-endian).
    //
    for (int i = 0; i < nCEs; i++)
    {
        unsigned short s = CE_SECONDARY(ces[i]);
        if (0 != s && pos + 2 <= nKeyMax)
        {
            key[pos++] = static_cast<UTF8>(s >> 8);
            key[pos++] = static_cast<UTF8>(s & 0xFF);
        }
    }

    // Level separator.
    //
    if (pos + 2 <= nKeyMax)
    {
        key[pos++] = 0;
        key[pos++] = 0;
    }

    // Level 3: tertiary weights (8-bit).
    //
    for (int i = 0; i < nCEs; i++)
    {
        unsigned char t = CE_TERTIARY(ces[i]);
        if (0 != t && pos + 1 <= nKeyMax)
        {
            key[pos++] = t;
        }
    }

    return pos;
}

// ---------------------------------------------------------------------------
// mux_collate_cmp_ci: Case-insensitive UCA comparison.
//
// Same as mux_collate_cmp but uses only Level 1 (primary) and Level 2
// (secondary) weights, skipping Level 3 (tertiary/case).  This gives
// natural case-insensitive ordering per UCA.
// ---------------------------------------------------------------------------

int mux_collate_cmp_ci(const UTF8 *a, size_t nA, const UTF8 *b, size_t nB)
{
    uint32_t cesA[MAX_SORT_CES];
    uint32_t cesB[MAX_SORT_CES];
    int nCEsA = CollectCEs(a, nA, cesA, MAX_SORT_CES);
    int nCEsB = CollectCEs(b, nB, cesB, MAX_SORT_CES);

    // Level 1: Compare primary weights.
    //
    int iA = 0, iB = 0;
    for (;;)
    {
        while (iA < nCEsA && 0 == CE_PRIMARY(cesA[iA]))
        {
            iA++;
        }
        while (iB < nCEsB && 0 == CE_PRIMARY(cesB[iB]))
        {
            iB++;
        }

        if (iA >= nCEsA || iB >= nCEsB)
        {
            break;
        }

        unsigned short pA = CE_PRIMARY(cesA[iA]);
        unsigned short pB = CE_PRIMARY(cesB[iB]);
        if (pA < pB) return -1;
        if (pA > pB) return 1;

        iA++;
        iB++;
    }

    while (iA < nCEsA && 0 == CE_PRIMARY(cesA[iA])) iA++;
    while (iB < nCEsB && 0 == CE_PRIMARY(cesB[iB])) iB++;
    if (iA < nCEsA) return 1;
    if (iB < nCEsB) return -1;

    // Level 2: Compare secondary weights.
    //
    iA = 0;
    iB = 0;
    for (;;)
    {
        while (iA < nCEsA && 0 == CE_SECONDARY(cesA[iA]))
        {
            iA++;
        }
        while (iB < nCEsB && 0 == CE_SECONDARY(cesB[iB]))
        {
            iB++;
        }

        if (iA >= nCEsA || iB >= nCEsB)
        {
            break;
        }

        unsigned short sA = CE_SECONDARY(cesA[iA]);
        unsigned short sB = CE_SECONDARY(cesB[iB]);
        if (sA < sB) return -1;
        if (sA > sB) return 1;

        iA++;
        iB++;
    }

    while (iA < nCEsA && 0 == CE_SECONDARY(cesA[iA])) iA++;
    while (iB < nCEsB && 0 == CE_SECONDARY(cesB[iB])) iB++;
    if (iA < nCEsA) return 1;
    if (iB < nCEsB) return -1;

    // No Level 3 -- case-insensitive.  No tiebreaker.
    //
    return 0;
}

// ---------------------------------------------------------------------------
// mux_collate_sortkey_ci: Case-insensitive sort key generation.
//
// Same as mux_collate_sortkey but omits Level 3 (tertiary/case) weights.
// Sort keys compare equal for strings that differ only in case.
// ---------------------------------------------------------------------------

size_t mux_collate_sortkey_ci(const UTF8 *src, size_t nSrc,
                              UTF8 *key, size_t nKeyMax)
{
    uint32_t ces[MAX_SORT_CES];
    int nCEs = CollectCEs(src, nSrc, ces, MAX_SORT_CES);

    size_t pos = 0;

    // Level 1: primary weights (16-bit big-endian).
    //
    for (int i = 0; i < nCEs; i++)
    {
        unsigned short p = CE_PRIMARY(ces[i]);
        if (0 != p && pos + 2 <= nKeyMax)
        {
            key[pos++] = static_cast<UTF8>(p >> 8);
            key[pos++] = static_cast<UTF8>(p & 0xFF);
        }
    }

    // Level separator.
    //
    if (pos + 2 <= nKeyMax)
    {
        key[pos++] = 0;
        key[pos++] = 0;
    }

    // Level 2: secondary weights (16-bit big-endian).
    //
    for (int i = 0; i < nCEs; i++)
    {
        unsigned short s = CE_SECONDARY(ces[i]);
        if (0 != s && pos + 2 <= nKeyMax)
        {
            key[pos++] = static_cast<UTF8>(s >> 8);
            key[pos++] = static_cast<UTF8>(s & 0xFF);
        }
    }

    // No Level 3 -- case-insensitive.
    //
    return pos;
}
