#!/usr/bin/env python3
"""Generate auto-discovered smoke suite list overrides.

Reads top-level `testcases/*.mux` files, excludes harness/setup files that are
not themselves smoke tests, and emits formatted MUX commands that override
`&suite.list.1` / `&suite.list.2` on the `smoke` object.
"""

from pathlib import Path
import sys


EXCLUDED = {"0upload.mux", "smoke.mux"}


def discover_names(tc_dir: Path):
    return sorted(
        path.stem for path in tc_dir.glob("*.mux")
        if path.name not in EXCLUDED
    )


def wrap_names(names, width=78):
    lines = []
    current = []
    current_len = 0
    for name in names:
        extra = len(name) + (1 if current else 0)
        if current and current_len + extra > width:
            lines.append(" ".join(current) + " \\")
            current = [name]
            current_len = len(name)
        else:
            current.append(name)
            current_len += extra
    if current:
        lines.append(" ".join(current))
    return lines


def emit_suite_attr(attr_name, names):
    print(f"&{attr_name} smoke=")
    for line in wrap_names(names):
        print(f"  {line}")
    print("-")


def main() -> int:
    tc_dir = Path(__file__).resolve().parent.parent
    discovered = discover_names(tc_dir)
    requested = [Path(arg).stem for arg in sys.argv[1:]]
    if requested:
        discovered_set = set(discovered)
        missing = [name for name in requested if name not in discovered_set]
        if missing:
            print("ERROR: unknown smoke tests:", ", ".join(missing), file=sys.stderr)
            return 1
        names = sorted(dict.fromkeys(requested))
    else:
        names = discovered
    if not names:
        print("ERROR: no discoverable smoke tests found", file=sys.stderr)
        return 1

    midpoint = (len(names) + 1) // 2
    first = names[:midpoint]
    second = names[midpoint:]

    print("#")
    print("# Auto-generated smoke suite overrides.")
    print("# Generated by testcases/tools/generate_smoke_suite.py.")
    print("#")
    emit_suite_attr("suite.list.1", first)
    emit_suite_attr("suite.list.2", second)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
