// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hydra.proto

#include "hydra.pb.h"
#include "hydra.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hydra {

static const char* HydraService_method_names[] = {
  "/hydra.HydraService/Authenticate",
  "/hydra.HydraService/CreateAccount",
  "/hydra.HydraService/GetSession",
  "/hydra.HydraService/DetachSession",
  "/hydra.HydraService/DestroySession",
  "/hydra.HydraService/Ping",
  "/hydra.HydraService/ListGames",
  "/hydra.HydraService/Connect",
  "/hydra.HydraService/SwitchLink",
  "/hydra.HydraService/DisconnectLink",
  "/hydra.HydraService/ListLinks",
  "/hydra.HydraService/GameSession",
  "/hydra.HydraService/SendInput",
  "/hydra.HydraService/Subscribe",
  "/hydra.HydraService/SubscribeGmcp",
  "/hydra.HydraService/GetScrollBack",
  "/hydra.HydraService/AddCredential",
  "/hydra.HydraService/DeleteCredential",
  "/hydra.HydraService/ListCredentials",
  "/hydra.HydraService/StartGame",
  "/hydra.HydraService/StopGame",
  "/hydra.HydraService/RestartGame",
  "/hydra.HydraService/GetGameStatus",
};

std::unique_ptr< HydraService::Stub> HydraService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HydraService::Stub> stub(new HydraService::Stub(channel, options));
  return stub;
}

HydraService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Authenticate_(HydraService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateAccount_(HydraService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSession_(HydraService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DetachSession_(HydraService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DestroySession_(HydraService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ping_(HydraService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListGames_(HydraService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Connect_(HydraService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SwitchLink_(HydraService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DisconnectLink_(HydraService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListLinks_(HydraService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GameSession_(HydraService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SendInput_(HydraService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(HydraService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SubscribeGmcp_(HydraService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetScrollBack_(HydraService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddCredential_(HydraService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteCredential_(HydraService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListCredentials_(HydraService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartGame_(HydraService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopGame_(HydraService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RestartGame_(HydraService_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetGameStatus_(HydraService_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HydraService::Stub::Authenticate(::grpc::ClientContext* context, const ::hydra::AuthRequest& request, ::hydra::AuthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::AuthRequest, ::hydra::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Authenticate_, context, request, response);
}

void HydraService::Stub::async::Authenticate(::grpc::ClientContext* context, const ::hydra::AuthRequest* request, ::hydra::AuthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::AuthRequest, ::hydra::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Authenticate_, context, request, response, std::move(f));
}

void HydraService::Stub::async::Authenticate(::grpc::ClientContext* context, const ::hydra::AuthRequest* request, ::hydra::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Authenticate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::AuthResponse>* HydraService::Stub::PrepareAsyncAuthenticateRaw(::grpc::ClientContext* context, const ::hydra::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::AuthResponse, ::hydra::AuthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Authenticate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::AuthResponse>* HydraService::Stub::AsyncAuthenticateRaw(::grpc::ClientContext* context, const ::hydra::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthenticateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::CreateAccount(::grpc::ClientContext* context, const ::hydra::CreateAccountRequest& request, ::hydra::CreateAccountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::CreateAccountRequest, ::hydra::CreateAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateAccount_, context, request, response);
}

void HydraService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::hydra::CreateAccountRequest* request, ::hydra::CreateAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::CreateAccountRequest, ::hydra::CreateAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, std::move(f));
}

void HydraService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::hydra::CreateAccountRequest* request, ::hydra::CreateAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::CreateAccountResponse>* HydraService::Stub::PrepareAsyncCreateAccountRaw(::grpc::ClientContext* context, const ::hydra::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::CreateAccountResponse, ::hydra::CreateAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::CreateAccountResponse>* HydraService::Stub::AsyncCreateAccountRaw(::grpc::ClientContext* context, const ::hydra::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::GetSession(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::hydra::SessionInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::SessionRequest, ::hydra::SessionInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSession_, context, request, response);
}

void HydraService::Stub::async::GetSession(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::SessionInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::SessionRequest, ::hydra::SessionInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSession_, context, request, response, std::move(f));
}

void HydraService::Stub::async::GetSession(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::SessionInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::SessionInfo>* HydraService::Stub::PrepareAsyncGetSessionRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::SessionInfo, ::hydra::SessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::SessionInfo>* HydraService::Stub::AsyncGetSessionRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::DetachSession(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::hydra::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DetachSession_, context, request, response);
}

void HydraService::Stub::async::DetachSession(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DetachSession_, context, request, response, std::move(f));
}

void HydraService::Stub::async::DetachSession(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DetachSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::Empty>* HydraService::Stub::PrepareAsyncDetachSessionRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::Empty, ::hydra::SessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DetachSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::Empty>* HydraService::Stub::AsyncDetachSessionRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDetachSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::DestroySession(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::hydra::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DestroySession_, context, request, response);
}

void HydraService::Stub::async::DestroySession(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DestroySession_, context, request, response, std::move(f));
}

void HydraService::Stub::async::DestroySession(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DestroySession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::Empty>* HydraService::Stub::PrepareAsyncDestroySessionRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::Empty, ::hydra::SessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DestroySession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::Empty>* HydraService::Stub::AsyncDestroySessionRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDestroySessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::Ping(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::hydra::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void HydraService::Stub::async::Ping(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void HydraService::Stub::async::Ping(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::Empty>* HydraService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::Empty, ::hydra::SessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::Empty>* HydraService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::ListGames(::grpc::ClientContext* context, const ::hydra::Empty& request, ::hydra::GameList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::Empty, ::hydra::GameList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListGames_, context, request, response);
}

void HydraService::Stub::async::ListGames(::grpc::ClientContext* context, const ::hydra::Empty* request, ::hydra::GameList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::Empty, ::hydra::GameList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListGames_, context, request, response, std::move(f));
}

void HydraService::Stub::async::ListGames(::grpc::ClientContext* context, const ::hydra::Empty* request, ::hydra::GameList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListGames_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameList>* HydraService::Stub::PrepareAsyncListGamesRaw(::grpc::ClientContext* context, const ::hydra::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::GameList, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListGames_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameList>* HydraService::Stub::AsyncListGamesRaw(::grpc::ClientContext* context, const ::hydra::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListGamesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::Connect(::grpc::ClientContext* context, const ::hydra::ConnectRequest& request, ::hydra::ConnectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::ConnectRequest, ::hydra::ConnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Connect_, context, request, response);
}

void HydraService::Stub::async::Connect(::grpc::ClientContext* context, const ::hydra::ConnectRequest* request, ::hydra::ConnectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::ConnectRequest, ::hydra::ConnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, std::move(f));
}

void HydraService::Stub::async::Connect(::grpc::ClientContext* context, const ::hydra::ConnectRequest* request, ::hydra::ConnectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::ConnectResponse>* HydraService::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::hydra::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::ConnectResponse, ::hydra::ConnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Connect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::ConnectResponse>* HydraService::Stub::AsyncConnectRaw(::grpc::ClientContext* context, const ::hydra::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::SwitchLink(::grpc::ClientContext* context, const ::hydra::SwitchRequest& request, ::hydra::SwitchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::SwitchRequest, ::hydra::SwitchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SwitchLink_, context, request, response);
}

void HydraService::Stub::async::SwitchLink(::grpc::ClientContext* context, const ::hydra::SwitchRequest* request, ::hydra::SwitchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::SwitchRequest, ::hydra::SwitchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SwitchLink_, context, request, response, std::move(f));
}

void HydraService::Stub::async::SwitchLink(::grpc::ClientContext* context, const ::hydra::SwitchRequest* request, ::hydra::SwitchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SwitchLink_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::SwitchResponse>* HydraService::Stub::PrepareAsyncSwitchLinkRaw(::grpc::ClientContext* context, const ::hydra::SwitchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::SwitchResponse, ::hydra::SwitchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SwitchLink_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::SwitchResponse>* HydraService::Stub::AsyncSwitchLinkRaw(::grpc::ClientContext* context, const ::hydra::SwitchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSwitchLinkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::DisconnectLink(::grpc::ClientContext* context, const ::hydra::DisconnectRequest& request, ::hydra::DisconnectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::DisconnectRequest, ::hydra::DisconnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DisconnectLink_, context, request, response);
}

void HydraService::Stub::async::DisconnectLink(::grpc::ClientContext* context, const ::hydra::DisconnectRequest* request, ::hydra::DisconnectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::DisconnectRequest, ::hydra::DisconnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DisconnectLink_, context, request, response, std::move(f));
}

void HydraService::Stub::async::DisconnectLink(::grpc::ClientContext* context, const ::hydra::DisconnectRequest* request, ::hydra::DisconnectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DisconnectLink_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::DisconnectResponse>* HydraService::Stub::PrepareAsyncDisconnectLinkRaw(::grpc::ClientContext* context, const ::hydra::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::DisconnectResponse, ::hydra::DisconnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DisconnectLink_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::DisconnectResponse>* HydraService::Stub::AsyncDisconnectLinkRaw(::grpc::ClientContext* context, const ::hydra::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDisconnectLinkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::ListLinks(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::hydra::LinkList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::SessionRequest, ::hydra::LinkList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListLinks_, context, request, response);
}

void HydraService::Stub::async::ListLinks(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::LinkList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::SessionRequest, ::hydra::LinkList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLinks_, context, request, response, std::move(f));
}

void HydraService::Stub::async::ListLinks(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::hydra::LinkList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLinks_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::LinkList>* HydraService::Stub::PrepareAsyncListLinksRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::LinkList, ::hydra::SessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListLinks_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::LinkList>* HydraService::Stub::AsyncListLinksRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListLinksRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::hydra::ClientMessage, ::hydra::ServerMessage>* HydraService::Stub::GameSessionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::hydra::ClientMessage, ::hydra::ServerMessage>::Create(channel_.get(), rpcmethod_GameSession_, context);
}

void HydraService::Stub::async::GameSession(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::hydra::ClientMessage,::hydra::ServerMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::hydra::ClientMessage,::hydra::ServerMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_GameSession_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::hydra::ClientMessage, ::hydra::ServerMessage>* HydraService::Stub::AsyncGameSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::hydra::ClientMessage, ::hydra::ServerMessage>::Create(channel_.get(), cq, rpcmethod_GameSession_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::hydra::ClientMessage, ::hydra::ServerMessage>* HydraService::Stub::PrepareAsyncGameSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::hydra::ClientMessage, ::hydra::ServerMessage>::Create(channel_.get(), cq, rpcmethod_GameSession_, context, false, nullptr);
}

::grpc::Status HydraService::Stub::SendInput(::grpc::ClientContext* context, const ::hydra::InputRequest& request, ::hydra::InputResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::InputRequest, ::hydra::InputResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendInput_, context, request, response);
}

void HydraService::Stub::async::SendInput(::grpc::ClientContext* context, const ::hydra::InputRequest* request, ::hydra::InputResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::InputRequest, ::hydra::InputResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendInput_, context, request, response, std::move(f));
}

void HydraService::Stub::async::SendInput(::grpc::ClientContext* context, const ::hydra::InputRequest* request, ::hydra::InputResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendInput_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::InputResponse>* HydraService::Stub::PrepareAsyncSendInputRaw(::grpc::ClientContext* context, const ::hydra::InputRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::InputResponse, ::hydra::InputRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendInput_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::InputResponse>* HydraService::Stub::AsyncSendInputRaw(::grpc::ClientContext* context, const ::hydra::InputRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendInputRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::hydra::GameOutput>* HydraService::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hydra::GameOutput>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void HydraService::Stub::async::Subscribe(::grpc::ClientContext* context, const ::hydra::SessionRequest* request, ::grpc::ClientReadReactor< ::hydra::GameOutput>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hydra::GameOutput>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hydra::GameOutput>* HydraService::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hydra::GameOutput>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hydra::GameOutput>* HydraService::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::hydra::SessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hydra::GameOutput>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::ClientReader< ::hydra::GmcpMessage>* HydraService::Stub::SubscribeGmcpRaw(::grpc::ClientContext* context, const ::hydra::GmcpSubscribeRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hydra::GmcpMessage>::Create(channel_.get(), rpcmethod_SubscribeGmcp_, context, request);
}

void HydraService::Stub::async::SubscribeGmcp(::grpc::ClientContext* context, const ::hydra::GmcpSubscribeRequest* request, ::grpc::ClientReadReactor< ::hydra::GmcpMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hydra::GmcpMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeGmcp_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hydra::GmcpMessage>* HydraService::Stub::AsyncSubscribeGmcpRaw(::grpc::ClientContext* context, const ::hydra::GmcpSubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hydra::GmcpMessage>::Create(channel_.get(), cq, rpcmethod_SubscribeGmcp_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hydra::GmcpMessage>* HydraService::Stub::PrepareAsyncSubscribeGmcpRaw(::grpc::ClientContext* context, const ::hydra::GmcpSubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hydra::GmcpMessage>::Create(channel_.get(), cq, rpcmethod_SubscribeGmcp_, context, request, false, nullptr);
}

::grpc::Status HydraService::Stub::GetScrollBack(::grpc::ClientContext* context, const ::hydra::ScrollBackRequest& request, ::hydra::ScrollBackResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::ScrollBackRequest, ::hydra::ScrollBackResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetScrollBack_, context, request, response);
}

void HydraService::Stub::async::GetScrollBack(::grpc::ClientContext* context, const ::hydra::ScrollBackRequest* request, ::hydra::ScrollBackResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::ScrollBackRequest, ::hydra::ScrollBackResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetScrollBack_, context, request, response, std::move(f));
}

void HydraService::Stub::async::GetScrollBack(::grpc::ClientContext* context, const ::hydra::ScrollBackRequest* request, ::hydra::ScrollBackResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetScrollBack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::ScrollBackResponse>* HydraService::Stub::PrepareAsyncGetScrollBackRaw(::grpc::ClientContext* context, const ::hydra::ScrollBackRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::ScrollBackResponse, ::hydra::ScrollBackRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetScrollBack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::ScrollBackResponse>* HydraService::Stub::AsyncGetScrollBackRaw(::grpc::ClientContext* context, const ::hydra::ScrollBackRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetScrollBackRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::AddCredential(::grpc::ClientContext* context, const ::hydra::AddCredentialRequest& request, ::hydra::AddCredentialResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::AddCredentialRequest, ::hydra::AddCredentialResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddCredential_, context, request, response);
}

void HydraService::Stub::async::AddCredential(::grpc::ClientContext* context, const ::hydra::AddCredentialRequest* request, ::hydra::AddCredentialResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::AddCredentialRequest, ::hydra::AddCredentialResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddCredential_, context, request, response, std::move(f));
}

void HydraService::Stub::async::AddCredential(::grpc::ClientContext* context, const ::hydra::AddCredentialRequest* request, ::hydra::AddCredentialResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddCredential_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::AddCredentialResponse>* HydraService::Stub::PrepareAsyncAddCredentialRaw(::grpc::ClientContext* context, const ::hydra::AddCredentialRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::AddCredentialResponse, ::hydra::AddCredentialRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddCredential_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::AddCredentialResponse>* HydraService::Stub::AsyncAddCredentialRaw(::grpc::ClientContext* context, const ::hydra::AddCredentialRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddCredentialRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::DeleteCredential(::grpc::ClientContext* context, const ::hydra::DeleteCredentialRequest& request, ::hydra::DeleteCredentialResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::DeleteCredentialRequest, ::hydra::DeleteCredentialResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteCredential_, context, request, response);
}

void HydraService::Stub::async::DeleteCredential(::grpc::ClientContext* context, const ::hydra::DeleteCredentialRequest* request, ::hydra::DeleteCredentialResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::DeleteCredentialRequest, ::hydra::DeleteCredentialResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteCredential_, context, request, response, std::move(f));
}

void HydraService::Stub::async::DeleteCredential(::grpc::ClientContext* context, const ::hydra::DeleteCredentialRequest* request, ::hydra::DeleteCredentialResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteCredential_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::DeleteCredentialResponse>* HydraService::Stub::PrepareAsyncDeleteCredentialRaw(::grpc::ClientContext* context, const ::hydra::DeleteCredentialRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::DeleteCredentialResponse, ::hydra::DeleteCredentialRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteCredential_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::DeleteCredentialResponse>* HydraService::Stub::AsyncDeleteCredentialRaw(::grpc::ClientContext* context, const ::hydra::DeleteCredentialRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteCredentialRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::ListCredentials(::grpc::ClientContext* context, const ::hydra::ListCredentialsRequest& request, ::hydra::ListCredentialsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::ListCredentialsRequest, ::hydra::ListCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListCredentials_, context, request, response);
}

void HydraService::Stub::async::ListCredentials(::grpc::ClientContext* context, const ::hydra::ListCredentialsRequest* request, ::hydra::ListCredentialsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::ListCredentialsRequest, ::hydra::ListCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCredentials_, context, request, response, std::move(f));
}

void HydraService::Stub::async::ListCredentials(::grpc::ClientContext* context, const ::hydra::ListCredentialsRequest* request, ::hydra::ListCredentialsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCredentials_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::ListCredentialsResponse>* HydraService::Stub::PrepareAsyncListCredentialsRaw(::grpc::ClientContext* context, const ::hydra::ListCredentialsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::ListCredentialsResponse, ::hydra::ListCredentialsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListCredentials_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::ListCredentialsResponse>* HydraService::Stub::AsyncListCredentialsRaw(::grpc::ClientContext* context, const ::hydra::ListCredentialsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListCredentialsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::StartGame(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::hydra::GameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartGame_, context, request, response);
}

void HydraService::Stub::async::StartGame(::grpc::ClientContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartGame_, context, request, response, std::move(f));
}

void HydraService::Stub::async::StartGame(::grpc::ClientContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameResponse>* HydraService::Stub::PrepareAsyncStartGameRaw(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::GameResponse, ::hydra::GameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameResponse>* HydraService::Stub::AsyncStartGameRaw(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::StopGame(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::hydra::GameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopGame_, context, request, response);
}

void HydraService::Stub::async::StopGame(::grpc::ClientContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopGame_, context, request, response, std::move(f));
}

void HydraService::Stub::async::StopGame(::grpc::ClientContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameResponse>* HydraService::Stub::PrepareAsyncStopGameRaw(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::GameResponse, ::hydra::GameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameResponse>* HydraService::Stub::AsyncStopGameRaw(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::RestartGame(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::hydra::GameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RestartGame_, context, request, response);
}

void HydraService::Stub::async::RestartGame(::grpc::ClientContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestartGame_, context, request, response, std::move(f));
}

void HydraService::Stub::async::RestartGame(::grpc::ClientContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestartGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameResponse>* HydraService::Stub::PrepareAsyncRestartGameRaw(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::GameResponse, ::hydra::GameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RestartGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameResponse>* HydraService::Stub::AsyncRestartGameRaw(::grpc::ClientContext* context, const ::hydra::GameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRestartGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HydraService::Stub::GetGameStatus(::grpc::ClientContext* context, const ::hydra::GameStatusRequest& request, ::hydra::GameStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hydra::GameStatusRequest, ::hydra::GameStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetGameStatus_, context, request, response);
}

void HydraService::Stub::async::GetGameStatus(::grpc::ClientContext* context, const ::hydra::GameStatusRequest* request, ::hydra::GameStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hydra::GameStatusRequest, ::hydra::GameStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGameStatus_, context, request, response, std::move(f));
}

void HydraService::Stub::async::GetGameStatus(::grpc::ClientContext* context, const ::hydra::GameStatusRequest* request, ::hydra::GameStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGameStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameStatusResponse>* HydraService::Stub::PrepareAsyncGetGameStatusRaw(::grpc::ClientContext* context, const ::hydra::GameStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hydra::GameStatusResponse, ::hydra::GameStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetGameStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hydra::GameStatusResponse>* HydraService::Stub::AsyncGetGameStatusRaw(::grpc::ClientContext* context, const ::hydra::GameStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetGameStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

HydraService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::AuthRequest, ::hydra::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::AuthRequest* req,
             ::hydra::AuthResponse* resp) {
               return service->Authenticate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::CreateAccountRequest, ::hydra::CreateAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::CreateAccountRequest* req,
             ::hydra::CreateAccountResponse* resp) {
               return service->CreateAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::SessionRequest, ::hydra::SessionInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SessionRequest* req,
             ::hydra::SessionInfo* resp) {
               return service->GetSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SessionRequest* req,
             ::hydra::Empty* resp) {
               return service->DetachSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SessionRequest* req,
             ::hydra::Empty* resp) {
               return service->DestroySession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::SessionRequest, ::hydra::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SessionRequest* req,
             ::hydra::Empty* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::Empty, ::hydra::GameList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::Empty* req,
             ::hydra::GameList* resp) {
               return service->ListGames(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::ConnectRequest, ::hydra::ConnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::ConnectRequest* req,
             ::hydra::ConnectResponse* resp) {
               return service->Connect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::SwitchRequest, ::hydra::SwitchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SwitchRequest* req,
             ::hydra::SwitchResponse* resp) {
               return service->SwitchLink(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::DisconnectRequest, ::hydra::DisconnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::DisconnectRequest* req,
             ::hydra::DisconnectResponse* resp) {
               return service->DisconnectLink(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::SessionRequest, ::hydra::LinkList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SessionRequest* req,
             ::hydra::LinkList* resp) {
               return service->ListLinks(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[11],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< HydraService::Service, ::hydra::ClientMessage, ::hydra::ServerMessage>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::hydra::ServerMessage,
             ::hydra::ClientMessage>* stream) {
               return service->GameSession(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::InputRequest, ::hydra::InputResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::InputRequest* req,
             ::hydra::InputResponse* resp) {
               return service->SendInput(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[13],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< HydraService::Service, ::hydra::SessionRequest, ::hydra::GameOutput>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::SessionRequest* req,
             ::grpc::ServerWriter<::hydra::GameOutput>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[14],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< HydraService::Service, ::hydra::GmcpSubscribeRequest, ::hydra::GmcpMessage>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::GmcpSubscribeRequest* req,
             ::grpc::ServerWriter<::hydra::GmcpMessage>* writer) {
               return service->SubscribeGmcp(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::ScrollBackRequest, ::hydra::ScrollBackResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::ScrollBackRequest* req,
             ::hydra::ScrollBackResponse* resp) {
               return service->GetScrollBack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::AddCredentialRequest, ::hydra::AddCredentialResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::AddCredentialRequest* req,
             ::hydra::AddCredentialResponse* resp) {
               return service->AddCredential(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::DeleteCredentialRequest, ::hydra::DeleteCredentialResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::DeleteCredentialRequest* req,
             ::hydra::DeleteCredentialResponse* resp) {
               return service->DeleteCredential(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::ListCredentialsRequest, ::hydra::ListCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::ListCredentialsRequest* req,
             ::hydra::ListCredentialsResponse* resp) {
               return service->ListCredentials(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::GameRequest* req,
             ::hydra::GameResponse* resp) {
               return service->StartGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::GameRequest* req,
             ::hydra::GameResponse* resp) {
               return service->StopGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::GameRequest, ::hydra::GameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::GameRequest* req,
             ::hydra::GameResponse* resp) {
               return service->RestartGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HydraService_method_names[22],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HydraService::Service, ::hydra::GameStatusRequest, ::hydra::GameStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HydraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hydra::GameStatusRequest* req,
             ::hydra::GameStatusResponse* resp) {
               return service->GetGameStatus(ctx, req, resp);
             }, this)));
}

HydraService::Service::~Service() {
}

::grpc::Status HydraService::Service::Authenticate(::grpc::ServerContext* context, const ::hydra::AuthRequest* request, ::hydra::AuthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::CreateAccount(::grpc::ServerContext* context, const ::hydra::CreateAccountRequest* request, ::hydra::CreateAccountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::GetSession(::grpc::ServerContext* context, const ::hydra::SessionRequest* request, ::hydra::SessionInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::DetachSession(::grpc::ServerContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::DestroySession(::grpc::ServerContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::Ping(::grpc::ServerContext* context, const ::hydra::SessionRequest* request, ::hydra::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::ListGames(::grpc::ServerContext* context, const ::hydra::Empty* request, ::hydra::GameList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::Connect(::grpc::ServerContext* context, const ::hydra::ConnectRequest* request, ::hydra::ConnectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::SwitchLink(::grpc::ServerContext* context, const ::hydra::SwitchRequest* request, ::hydra::SwitchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::DisconnectLink(::grpc::ServerContext* context, const ::hydra::DisconnectRequest* request, ::hydra::DisconnectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::ListLinks(::grpc::ServerContext* context, const ::hydra::SessionRequest* request, ::hydra::LinkList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::GameSession(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::hydra::ServerMessage, ::hydra::ClientMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::SendInput(::grpc::ServerContext* context, const ::hydra::InputRequest* request, ::hydra::InputResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::Subscribe(::grpc::ServerContext* context, const ::hydra::SessionRequest* request, ::grpc::ServerWriter< ::hydra::GameOutput>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::SubscribeGmcp(::grpc::ServerContext* context, const ::hydra::GmcpSubscribeRequest* request, ::grpc::ServerWriter< ::hydra::GmcpMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::GetScrollBack(::grpc::ServerContext* context, const ::hydra::ScrollBackRequest* request, ::hydra::ScrollBackResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::AddCredential(::grpc::ServerContext* context, const ::hydra::AddCredentialRequest* request, ::hydra::AddCredentialResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::DeleteCredential(::grpc::ServerContext* context, const ::hydra::DeleteCredentialRequest* request, ::hydra::DeleteCredentialResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::ListCredentials(::grpc::ServerContext* context, const ::hydra::ListCredentialsRequest* request, ::hydra::ListCredentialsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::StartGame(::grpc::ServerContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::StopGame(::grpc::ServerContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::RestartGame(::grpc::ServerContext* context, const ::hydra::GameRequest* request, ::hydra::GameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HydraService::Service::GetGameStatus(::grpc::ServerContext* context, const ::hydra::GameStatusRequest* request, ::hydra::GameStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hydra

