#!/usr/bin/perl
# Parse allkeys.txt (DUCET) and produce:
#   1. tr_ducet.txt        -- single-CP entries: CODEPOINT;CE_INDEX
#   2. tr_ducet_contract.txt -- 2-CP contractions: CP1 CP2;CE_INDEX
#   3. ducet_cetable.h     -- C header with CE weight data
#
# CE index 0 is reserved as "not in DUCET -- use implicit weights."
# Real CE sequences start at index 1.
#
# 3-CP contractions (only 8 in Unicode 16.0) are emitted as a small
# hardcoded table in the C header.

use strict;
use warnings;

my $input = 'allkeys.txt';
open my $fh, '<', $input or die "Cannot open $input: $!\n";

# Parse all entries.
#   Key: stringified CP sequence ("0041" or "0438 0306")
#   Value: arrayref of CE arrayrefs [[p,s,t,var], [p,s,t,var], ...]
#
my @single_entries;     # [cp, ce_seq_key]
my @contract2_entries;  # [[cp1,cp2], ce_seq_key]
my @contract3_entries;  # [[cp1,cp2,cp3], ce_seq_key]

# Deduplicate CE sequences.
#   Key: stringified CE sequence
#   Value: assigned index (1-based)
#
my %ce_seq_index;
my @ce_seq_list;        # index 0 unused; index 1..N are real sequences
my $next_index = 1;

sub get_ce_index {
    my ($ces_ref) = @_;
    # Build a string key from the CE sequence.
    my $key = join(',', map { sprintf("%04X.%04X.%02X.%02X",
        $_->[0], $_->[1], $_->[2], $_->[3]) } @$ces_ref);
    unless (exists $ce_seq_index{$key}) {
        $ce_seq_index{$key} = $next_index;
        push @ce_seq_list, $ces_ref;
        $next_index++;
    }
    return $ce_seq_index{$key};
}

my $line_count = 0;
my $entry_count = 0;

while (<$fh>) {
    chomp;
    $line_count++;

    # Skip comments and directives.
    next if /^\s*#/ || /^\s*$/ || /^\@/;

    # Format: CP [CP ...] ; [.PPPP.SSSS.TTTT] [.PPPP.SSSS.TTTT] ... # comment
    # Or:     CP [CP ...] ; [*PPPP.SSSS.TTTT] ... (variable)
    unless (/^([0-9A-F][0-9A-F \t]+?)\s*;\s*(.+?)\s*#/) {
        # Try without comment.
        unless (/^([0-9A-F][0-9A-F \t]+?)\s*;\s*(.+?)\s*$/) {
            next;
        }
    }
    my ($cp_str, $ce_str) = ($1, $2);
    $entry_count++;

    # Parse code points.
    my @cps = map { hex($_) } split(/\s+/, $cp_str);

    # Parse CE sequence.
    my @ces;
    while ($ce_str =~ /\[([.\*])([0-9A-F]{4})\.([0-9A-F]{4})\.([0-9A-F]{4})\]/gi) {
        my $var = ($1 eq '*') ? 1 : 0;
        push @ces, [hex($2), hex($3), hex($4), $var];
    }

    unless (@ces) {
        warn "Line $line_count: no CEs parsed: $_\n";
        next;
    }

    my $idx = get_ce_index(\@ces);

    if (scalar @cps == 1) {
        push @single_entries, [$cps[0], $idx];
    } elsif (scalar @cps == 2) {
        push @contract2_entries, [[$cps[0], $cps[1]], $idx];
    } elsif (scalar @cps == 3) {
        push @contract3_entries, [[$cps[0], $cps[1], $cps[2]], $idx];
    } else {
        warn "Line $line_count: contraction with ", scalar @cps,
             " CPs (unsupported, skipping)\n";
    }
}
close $fh;

my $n_unique = $next_index - 1;
printf STDERR "Parsed %d entries, %d unique CE sequences.\n",
    $entry_count, $n_unique;
printf STDERR "  Single-CP: %d, 2-CP contractions: %d, 3-CP contractions: %d\n",
    scalar @single_entries, scalar @contract2_entries, scalar @contract3_entries;

# ---------------------------------------------------------------------------
# Output 1: tr_ducet.txt (for integers.exe)
# ---------------------------------------------------------------------------

# Sort by code point.
@single_entries = sort { $a->[0] <=> $b->[0] } @single_entries;

open my $out1, '>', 'tr_ducet.txt' or die "Cannot write tr_ducet.txt: $!\n";
for my $e (@single_entries) {
    printf $out1 "%04X;%d\n", $e->[0], $e->[1];
}
close $out1;
printf STDERR "Wrote tr_ducet.txt: %d entries, max index %d.\n",
    scalar @single_entries, $n_unique;

# ---------------------------------------------------------------------------
# Output 2: tr_ducet_contract.txt (for pairs.exe, 2-CP contractions only)
# ---------------------------------------------------------------------------

@contract2_entries = sort {
    $a->[0][0] <=> $b->[0][0] || $a->[0][1] <=> $b->[0][1]
} @contract2_entries;

open my $out2, '>', 'tr_ducet_contract.txt' or die "Cannot write tr_ducet_contract.txt: $!\n";
for my $e (@contract2_entries) {
    # CE index emitted as hex because pairs.exe parses field 1 as hex.
    printf $out2 "%04X %04X;%04X\n", $e->[0][0], $e->[0][1], $e->[1];
}
close $out2;
printf STDERR "Wrote tr_ducet_contract.txt: %d entries.\n",
    scalar @contract2_entries;

# ---------------------------------------------------------------------------
# Output 3: ducet_cetable.h (C header with CE data)
# ---------------------------------------------------------------------------

open my $out3, '>', '../mux/src/ducet_cetable.h'
    or die "Cannot write ducet_cetable.h: $!\n";

print $out3 <<'HEADER';
// ducet_cetable.h -- Generated by gen_ducet.pl from allkeys.txt (Unicode 16.0)
// DO NOT EDIT -- regenerate from utf/gen_ducet.pl.
//
// CE index 0 = sentinel (use implicit weights).
// Indices 1..N are real CE sequences from DUCET.

#ifndef DUCET_CETABLE_H
#define DUCET_CETABLE_H

HEADER

# Build flat CE weight array and offset table.
my @flat_weights;   # Flat array of packed uint32_t values.
my @offsets;        # offsets[i] = start index in flat_weights for CE seq i.
                    # Index 0 is the sentinel (empty).

push @offsets, 0;   # Sentinel: index 0 -> offset 0, length 0.

for my $i (0 .. $#ce_seq_list) {
    push @offsets, scalar @flat_weights;
    my $ces = $ce_seq_list[$i];
    for my $ce (@$ces) {
        # Pack: variable(1) | primary(15) in upper 16 bits, secondary(8), tertiary(8)
        # Actually: bit 31 = variable, bits 30..16 = primary(15 bits... no)
        # Primary range is 0000..72B6 which needs 15 bits (max 32767).
        # 72B6 = 29366 < 32768 = 2^15. OK, fits in 15 bits.
        # But let's just use full 32 bits cleanly:
        #   bits 31:    variable flag
        #   bits 30-16: primary (15 bits, sufficient for range 0..72B6)
        #   bits 15-8:  secondary (8 bits, range 0020..0126 = 32..294)
        # Wait, 294 > 255. Secondary needs more than 8 bits!

        # Secondary range: 0020..0126 = 32..294.  That's 9 bits.
        # Tertiary range: 0002..001F = 2..31.  That's 5 bits.
        # Primary range: 0200..72B6 = 512..29366.  That's 15 bits.
        # Total: 15 + 9 + 5 + 1(variable) = 30 bits.  Fits in 32!
        #
        # But packing 9-bit secondary is awkward.  Let's just store
        # as two 16-bit values:
        #   Word 0: (variable << 15) | primary
        #   Word 1: (secondary << 5) | tertiary
        # No wait, secondary is up to 294 which needs 9 bits, and
        # tertiary up to 31 which needs 5 bits.  9+5 = 14 bits, fits
        # in 16.  But (294 << 5) | 31 = 9439 + 31 = 9470 < 65536.  OK.
        #
        # Actually let's just use a simple struct-based approach.
        # Store as uint32_t: (primary << 16) | (secondary << 8) | tertiary
        # This only works if secondary fits in 8 bits.  It doesn't (max 294).
        #
        # OK, use two UINT16 values per CE:
        #   [0] = primary (with variable flag in bit 15... no, primary
        #         can be up to 72B6 = 0111 0010 1011 0110, bit 15 is 0.
        #         So bit 15 is free for the variable flag!)
        #   [1] = (secondary << 5) | tertiary
        #
        # primary max 72B6 (29366) < 32768 (2^15), so bit 15 is free.
        # variable flag goes in bit 15 of word 0.
        # secondary max 0126 (294), shifted left 5: 294*32 = 9408.
        # tertiary max 001F (31).
        # word 1 max: 9408 + 31 = 9439 < 65536.  Good.

        my $w0 = $ce->[0] | ($ce->[3] << 15);  # primary | (variable << 15)
        my $w1 = ($ce->[1] << 5) | $ce->[2];   # (secondary << 5) | tertiary

        # Pack into a single uint32_t for compact storage.
        my $packed = ($w0 << 16) | $w1;
        push @flat_weights, $packed;
    }
}
# Final sentinel offset.
push @offsets, scalar @flat_weights;

printf STDERR "CE table: %d unique sequences, %d total CEs (flat array).\n",
    $n_unique, scalar @flat_weights;

# Emit offset table.
my $n_offsets = scalar @offsets;
printf $out3 "// Offset table: ducet_ce_offset[i] is the start index in\n";
printf $out3 "// ducet_ce_weights[] for CE sequence i.  The number of CEs\n";
printf $out3 "// for sequence i is ducet_ce_offset[i+1] - ducet_ce_offset[i].\n";
printf $out3 "// Index 0 is the sentinel (no CEs = use implicit weights).\n";
printf $out3 "//\n";
printf $out3 "#define DUCET_CE_SEQUENCES %d\n\n", $n_unique;

# Choose offset type based on max value.
my $max_offset = $offsets[-1];
my $offset_type = ($max_offset <= 65535) ? 'unsigned short' : 'unsigned int';
printf $out3 "static const %s ducet_ce_offset[%d] =\n{\n", $offset_type, $n_offsets;
for (my $i = 0; $i < $n_offsets; $i++) {
    if ($i % 16 == 0) {
        print $out3 "    ";
    }
    printf $out3 "%5d", $offsets[$i];
    if ($i < $n_offsets - 1) {
        print $out3 ",";
        if (($i + 1) % 16 == 0) {
            print $out3 "\n";
        }
    }
}
print $out3 "\n};\n\n";

# Emit flat weight array.
my $n_weights = scalar @flat_weights;
printf $out3 "// Packed CE weights.  Each uint32_t encodes one CE:\n";
printf $out3 "//   Bits 31:    variable flag (1 = variable/shifted)\n";
printf $out3 "//   Bits 30-16: primary weight (0..0x72B6)\n";
printf $out3 "//   Bits 15-5:  secondary weight (0..0x0126)\n";
printf $out3 "//   Bits 4-0:   tertiary weight (0..0x001F)\n";
printf $out3 "//\n";
printf $out3 "// To unpack:\n";
printf $out3 "//   bool variable = (w >> 31) & 1;\n";
printf $out3 "//   unsigned short primary = (w >> 16) & 0x7FFF;\n";
printf $out3 "//   unsigned short secondary = (w >> 5) & 0x07FF;\n";
printf $out3 "//   unsigned char tertiary = w & 0x1F;\n";
printf $out3 "//\n";
printf $out3 "#define DUCET_CE_TOTAL %d\n\n", $n_weights;
printf $out3 "static const uint32_t ducet_ce_weights[%d] =\n{\n", $n_weights;
for (my $i = 0; $i < $n_weights; $i++) {
    if ($i % 8 == 0) {
        print $out3 "    ";
    }
    printf $out3 "0x%08X", $flat_weights[$i];
    if ($i < $n_weights - 1) {
        print $out3 ",";
        if (($i + 1) % 8 == 0) {
            print $out3 "\n";
        }
    }
}
print $out3 "\n};\n\n";

# Emit 3-CP contraction table.
if (@contract3_entries) {
    printf $out3 "// 3-CP contractions (only %d in Unicode 16.0).\n",
        scalar @contract3_entries;
    printf $out3 "// Checked at runtime before 2-CP contraction lookup.\n";
    printf $out3 "//\n";
    printf $out3 "#define DUCET_CONTRACT3_COUNT %d\n\n", scalar @contract3_entries;
    printf $out3 "static const struct {\n";
    printf $out3 "    uint32_t cp1, cp2, cp3;\n";
    printf $out3 "    unsigned short ce_index;\n";
    printf $out3 "} ducet_contract3[%d] =\n{\n", scalar @contract3_entries;
    for my $e (@contract3_entries) {
        printf $out3 "    { 0x%04X, 0x%04X, 0x%04X, %d },\n",
            $e->[0][0], $e->[0][1], $e->[0][2], $e->[1];
    }
    printf $out3 "};\n\n";
}

# Emit implicit weight parameters.
print $out3 <<'IMPLICIT';
// Implicit weight ranges from @implicitweights directives.
// Code points in these ranges get primary weights derived from:
//   primary = base + (cp - range_start)
// All other unassigned code points use UCA Section 10.1 algorithm.
//
// Range           Base   Description
// 17000..18AFF    FB00   Tangut and Tangut Components
// 18D00..18D7F    FB00   Tangut Supplement
// 1B170..1B2FF    FB01   Nushu
// 18B00..18CFF    FB02   Khitan Small Script
//
// Implicit weight computation is done at runtime in utf8_collate.cpp.

#endif // DUCET_CETABLE_H
IMPLICIT

close $out3;

printf STDERR "Wrote ducet_cetable.h: %d offsets, %d packed weights.\n",
    $n_offsets, $n_weights;
printf STDERR "  3-CP contractions: %d\n", scalar @contract3_entries;

# Verification: spot-check a few known entries.
sub verify {
    my ($label, $cp, $expected_ces) = @_;
    my $found = 0;
    for my $e (@single_entries) {
        if ($e->[0] == $cp) {
            my $idx = $e->[1];
            my $ces = $ce_seq_list[$idx - 1];
            my $got = join(' ', map { sprintf("[%04X.%04X.%04X]",
                $_->[0], $_->[1], $_->[2]) } @$ces);
            if ($got eq $expected_ces) {
                printf STDERR "  VERIFY OK: %s (U+%04X) -> %s\n", $label, $cp, $got;
            } else {
                printf STDERR "  VERIFY FAIL: %s (U+%04X)\n    expected: %s\n    got:      %s\n",
                    $label, $cp, $expected_ces, $got;
            }
            $found = 1;
            last;
        }
    }
    unless ($found) {
        printf STDERR "  VERIFY FAIL: %s (U+%04X) not found\n", $label, $cp;
    }
}

print STDERR "\nVerification:\n";
verify('LATIN SMALL LETTER A', 0x0061, '[2380.0020.0002]');
verify('LATIN CAPITAL LETTER A', 0x0041, '[2380.0020.0008]');
verify('LATIN SMALL LETTER E WITH ACUTE', 0x00E9, '[23E7.0020.0002] [0000.0024.0002]');
verify('SPACE', 0x0020, '[0209.0020.0002]');
verify('EXCLAMATION MARK', 0x0021, '[0269.0020.0002]');
