/*
 * unicode_tables_c.h — Unicode case mapping DFA tables for pure C.
 *
 * THIS FILE IS GENERATED by 'make' in the utf/ directory.
 * DO NOT EDIT — changes will be overwritten.
 *
 * Provides the same DFA-driven case mapping as mux_toupper/mux_tolower/
 * mux_totitle from stringutil.h, but as standalone C functions using
 * tables generated by the utf/ pipeline tools.
 *
 * DFA execution model:
 *   Feed bytes to the DFA one at a time.  When it reaches an accepting
 *   state, the state index encodes either "identity" (no change) or an
 *   index into the OTT (output text table).  OTT entries are either
 *   literal replacements or XOR masks.
 */

#ifndef UNICODE_TABLES_C_H
#define UNICODE_TABLES_C_H

#include <stddef.h>

/* Default LIBMUX_API when not provided by config.h. */
#ifndef LIBMUX_API
#if defined(_WIN32) || defined(WIN32)
#ifdef BUILDING_LIBMUX
#define LIBMUX_API __declspec(dllexport)
#else
#define LIBMUX_API __declspec(dllimport)
#endif
#else
#define LIBMUX_API
#endif
#endif

/* Equivalent to MUX's string_desc — holds a UTF-8 replacement string. */
typedef struct {
    size_t n_bytes;
    size_t n_points;
    const unsigned char *p;
} co_string_desc;

/* UTF-8 lead byte -> sequence length (1-4), 5=continuation, 6=illegal */
#define CO_UTF8_SIZE1     1
#define CO_UTF8_SIZE2     2
#define CO_UTF8_SIZE3     3
#define CO_UTF8_SIZE4     4
#define CO_UTF8_CONTINUE  5
#define CO_UTF8_ILLEGAL   6

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char utf8_FirstByte[256];

