#!/bin/sh
PATH=/bin:/usr/bin:
#
#	Check a MUX V2 flatfile.
#
case $# in
	1)	../bin/dbconvert $1 C >/dev/null 2>&1 ;;
	2)	../bin/dbconvert $1 C <$2 >/dev/null 2>&1 ;;
	3)	../bin/dbconvert $1 C <$2 >/dev/null 2>$3 ;;
	*)	echo Usage: $0 'basename [source_file [log_file]]'; exit 1 ;;
esac

exit 0
