#!/bin/sh
PATH=/bin:/usr/bin:
#
#	Load MUX V2 flatfile into MUX V2 database.
#
case $# in
	3)	../bin/netmux -d$1 -l -i$2 -o$3 ;;
	*)	echo Usage: $0 'basename flatfile structfile';
                echo i.e., $0 netmux netmux.flat netmux.db;
                exit 1 ;;
esac

exit 0
