#!/bin/sh
#
#   Export a MUX flatfile from the SQLite database.
#
#   Usage: db_unload <basename> <flatfile> [-C <comsys.db>] [-m <mail.db>]
#
#   Example: db_unload netmux netmux.flat
#            db_unload netmux netmux.flat -C comsys.db -m mail.db
#
#   Note: The server should not be running during export.
#

BIN=../bin

LD_LIBRARY_PATH=$BIN; export LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=$BIN; export DYLD_LIBRARY_PATH

case $# in
    2)  $BIN/dbconvert -d "$1" -u -o "$2" ;;
    4)  $BIN/dbconvert -d "$1" -u -o "$2" $3 "$4" ;;
    6)  $BIN/dbconvert -d "$1" -u -o "$2" $3 "$4" $5 "$6" ;;
    *)  echo "Usage: $0 <basename> <flatfile> [-C <comsys.db>] [-m <mail.db>]"
        echo "  e.g. $0 netmux netmux.flat"
        echo "       $0 netmux netmux.flat -C comsys.db -m mail.db"
        exit 1 ;;
esac

exit 0
