#!/bin/sh
LD_LIBRARY_PATH=../bin; export LD_LIBRARY_PATH
PATH=/bin:/usr/bin:
#
#	Unload a MUX V3 flatfile from MUX V3 database.
#
echo NOTE: Make sure the MUX is NOT running before you make a flatfile. 
case $# in
	3)	../bin/netmux -d$1 -u -i$2 -o$3 ;;
	*)	echo Usage: $0 'basename structfile flatfile';
                echo i.e., $0 netmux netmux.db.new netmux.flat;
                exit 1 ;;
esac

exit 0
